"""GENERATED by design/build_tokens.py from design/tokens.json -- do not edit by hand.

Colours are Qt-style '#AARRGGBB' strings (alpha FIRST -- not CSS's #RRGGBBAA; this is the
bug that tests/check_theme_colors.py in the-den-client exists to catch). Sizes are ints in px,
durations in ms. Copied into the-den-client/src/holt_tokens.py, which theme.py reads."""

COLOR = {
    'deep': '#FF0D0B12',
    'surface': '#FF171423',
    'raised': '#FF1D1927',
    'hairline': '#17FFFFFF',
    'hairline_strong': '#26FFFFFF',
    'ink': '#FFFFFFFF',
    'ink70': '#B2FFFFFF',
    'ink55': '#8CFFFFFF',
    'ink42': '#6BFFFFFF',
    'ink28': '#47FFFFFF',
    'current': '#FFB14DFF',
    'current_hover': '#FFC77DFF',
    'current_deep': '#FF8F2FE0',
    'current_tint': '#1AB14DFF',
    'lilac': '#FFF4EBFF',
    'healthy': '#FF28E0C8',
    'warning': '#FFFFB84D',
}

GLASS = {
    'surface': '#B2171423',
    'surface_strong': '#D6171423',
    'border': '#17FFFFFF',
    'border_strong': '#26FFFFFF',
    'highlight': '#0FFFFFFF',
    'highlight_strong': '#14FFFFFF',
    'blur': '18px',
    'blur_strong': '28px',
    'blur_badge': '8px',
    'saturate': '140%',
    'badge_surface': '#B80D0B12',
    'input_surface': '#800D0B12',
}

AMBIENT = {
    'glow_current': '#2EB14DFF',
    'glow_healthy': '#1228E0C8',
    'ring': '#0DF4EBFF',
    'scrim_strong': '#EB0D0B12',
    'scrim_mid': '#9E0D0B12',
    'scrim_weak': '#1F0D0B12',
    'stripe': '#3DB14DFF',
}

BADGE = {
    'available': '#FF28E0C8',
    'pending': '#FFB14DFF',
    'processing': '#FFB14DFF',
    'partial': '#FFFFB84D',
    'error': '#FFFFB84D',
    'missing': '#6BFFFFFF',
    'missing_dot': '#47FFFFFF',
}

FONT_CORE = 'Nunito'
FONT_MONO = 'JetBrains Mono'

TYPE = {
    'display': {'size': 42, 'weight': 900, 'tracking': -1.8, 'line_height': 0.98, 'mono': False, 'uppercase': False},
    'display_hero': {'size': 64, 'weight': 900, 'tracking': -2.6, 'line_height': 0.95, 'mono': False, 'uppercase': False},
    'page_title': {'size': 26, 'weight': 800, 'tracking': -1.2, 'line_height': 1.05, 'mono': False, 'uppercase': False},
    'section_title': {'size': 16, 'weight': 800, 'tracking': -0.4, 'line_height': 1.2, 'mono': False, 'uppercase': False},
    'wordmark': {'size': 20, 'weight': 900, 'tracking': -0.6, 'line_height': 1, 'mono': False, 'uppercase': False},
    'body': {'size': 15, 'weight': 400, 'tracking': 0, 'line_height': 1.6, 'mono': False, 'uppercase': False},
    'body_small': {'size': 13, 'weight': 400, 'tracking': 0, 'line_height': 1.55, 'mono': False, 'uppercase': False},
    'label': {'size': 13.5, 'weight': 700, 'tracking': 0, 'line_height': 1.2, 'mono': False, 'uppercase': False},
    'button': {'size': 12.5, 'weight': 800, 'tracking': -0.2, 'line_height': 1, 'mono': False, 'uppercase': False},
    'eyebrow': {'size': 10.5, 'weight': 400, 'tracking': 2.2, 'line_height': 1.2, 'mono': True, 'uppercase': True},
    'meta': {'size': 10.5, 'weight': 400, 'tracking': 0, 'line_height': 1.7, 'mono': True, 'uppercase': False},
    'field_label': {'size': 10.5, 'weight': 400, 'tracking': 1.2, 'line_height': 1.2, 'mono': True, 'uppercase': True},
}

RADIUS = {
    'sm': 8,
    'md': 10,
    'lg': 14,
    'pill': 999,
}

SPACE = {
    '1': 6,
    '2': 10,
    '3': 16,
    '4': 22,
    '5': 32,
    '6': 48,
}

SIZE = {
    'sidebar': 240,
    'sidebarRail': 72,
    'topBar': 60,
    'tabBar': 72,
    'contentMax': 1400,
    'posterSm': 112,
    'posterMd': 132,
    'posterLg': 148,
    'posterXl': 220,
    'avatar': 28,
    'hitTarget': 44,
    'mobileBreakpoint': 900,
}

MOTION_MS = {
    'fast': 160,
    'base': 220,
    'draw': 1600,
}
EASE_OUT = 'cubic-bezier(.2,.8,.2,1)'  # cubic-bezier control points
